#!/bin/sh
set -ex

if [[ "$target_platform" == osx-* ]] && [[ "$MACOSX_DEPLOYMENT_TARGET" == 11.* || "$MACOSX_DEPLOYMENT_TARGET" == "10.15" ]]; then
    CMAKE_ARGS="$CMAKE_ARGS -DCMake_HAVE_CXX_FILESYSTEM=1"
else
    CMAKE_ARGS="$CMAKE_ARGS -DCMake_HAVE_CXX_FILESYSTEM=0"
fi

cmake -LAH -G Ninja ${CMAKE_ARGS} \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_VERBOSE_MAKEFILE=1 \
    -DCMAKE_PREFIX_PATH=${PREFIX} \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_INSTALL_RPATH=${PREFIX}/lib \
    -DBUILD_CursesDialog=ON \
    -DCURSES_INCLUDE_PATH=${PREFIX}/include \
    -DCMAKE_USE_SYSTEM_LIBRARIES=ON \
    -DCMAKE_USE_SYSTEM_JSONCPP=OFF \
    -DCMAKE_USE_SYSTEM_LIBARCHIVE=OFF \
    -DCMAKE_USE_SYSTEM_CPPDAP=OFF \
    -DCMAKE_USE_SYSTEM_LIBRARY_JSONCPP=OFF \
    -DCMAKE_USE_SYSTEM_LIBRARY_LIBARCHIVE=OFF \
    -DCMAKE_USE_SYSTEM_LIBRARY_CPPDAP=OFF \
    -DBUILD_QtDialog=OFF \
    -DCMake_HAVE_CXX_MAKE_UNIQUE:INTERNAL=FALSE \
    . || (cat TryRunResults.cmake; false)

cmake --build . --target install --parallel ${CPU_COUNT}
